#!/bin/bash

logname=$1
pswd=$2
# sal=`tr -dc A-Za-z0-9 </dev/urandom | head -c 8`
uid=$3
gid=$4
home=$5
shell=$6

if grep "$logname" /etc/passwd &> /dev/null
then
        echo "ERROR: $logname ya está siendo usado"
else
        if grep "$uid" /etc/passwd &> /dev/null
                echo "ERROR: $uid inválido"
        else
                # Crear copia de seguridad
                cp /etc/passwd /etc/ptmp
                echo "$logname:x:$uid:$gid::$home:$shell" >> /etc/passwd
                hashpwd=`openssl passwd -1 "$pswd" -salt`
                now=$(($(date +%s) / 86400))
                echo "$logname:$hashpwd:$now:0:99999:7:::" >> /etc/shadow
                # Creando home y archivos
                mkdir -p "$home"
                cp -R /etc/skel/. "$home"
                cp /etc/ptmp
                chown -R "$username":"$gid" "$home"
                chmod 750 "$home"
                echo "Fin del proceso de creación del usuario $logname ( $uid )"
                rm /etc/ptmp
        fi
fi

